on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

permissions:
    contents: write
    packages: write

jobs:
    build-pdf:
        timeout-minutes: 5
        env:
          MARGIN: 25mm
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Set up npm
          uses: actions/setup-node@v3
          with:
            node-version: '22'
        - name: Set up Pandoc
          run: |
            sudo apt-get update
            sudo apt-get install -y pandoc
        - name: Install dependencies
          run: |
            npm install -g markdown-toc
            sudo apt-get install xvfb libfontconfig wkhtmltopdf
        - name: Generate Table of Contents
          run: |
            markdown-toc -i README.md
        - name: Add GitHub Version to README
          run: |
            GITHUB_HASH=$(git rev-parse --short HEAD)
            DATE=$(date +'%Y%m%d%H%M%S')
            GITHUB_REF_TEXT="\n\n*** \n\n_GitHub Version \`${GITHUB_HASH} (${DATE})\`_"
            echo -e "\n$GITHUB_REF_TEXT" >> README.md
        - name: Build PDF
          run: |
            pandoc README.md -o "Projektarbeit Go.pdf" --pdf-engine=wkhtmltopdf --css=./assets/pdf_style.css \
                  -V margin-top=${{ env.MARGIN }} -V margin-bottom=${{ env.MARGIN }} \
                  -V margin-left=${{ env.MARGIN }} -V margin-right=${{ env.MARGIN }} \
                  -V papersize=a4
        - name: Release PDF
          uses: ncipollo/release-action@v1
          with:
            artifacts: "Projektarbeit Go.pdf"
            tag: pdf-build-${{ github.run_id }}
            makeLatest: true